base:
    seed: &seed 42
model:
    type: WanT2V
    path: /home/hezhiye/hif8_quant/base_model/Wan2.1-T2V-1.3B
    torch_dtype: auto
calib:
    name: t2v
    download: True
    path: ../assets/wan_t2v/calib/
    stream_stats: False
    stream_chunk_size: 1
    sample_steps: 20
    bs: 1
    distributed_merge: False
    target_height: 480
    target_width: 832
    num_frames: 81
    guidance_scale: 5.0
    seed: *seed
eval:
    eval_pos: [transformed, fake_quant]
    type: video_gen
    name: t2v
    download: True
    path: ../assets/wan_t2v/calib/
    bs: 1
    distributed: False
    target_height: 480
    target_width: 832
    num_frames: 81
    guidance_scale: 5.0
    output_video_path: ./output_videos_htg_hif8/
quant:
    video_gen:
        method: HTG
        weight:
            quant_type: hif8-quant
            bit: hif8
            symmetric: True
            granularity: per_channel
        act:
            quant_type: hif8-quant
            bit: hif8
            symmetric: True
            granularity: per_token
        special:
            alpha: 0.99
            group_ratio: 10
            min_group_num: 1
            enable_dynamic_runtime: True
save:
    save_lightx2v: True
    save_path: /home/hezhiye/hif8_quant/quant_model/wan_htg_w8a8_hif8/
